- hosts: "{{ hosts_pattern | default('localhost') }}"
  become: yes
  tasks:
    - name: Download CentOS Image
      ansible.builtin.get_url:
        url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1809.qcow2
        dest: /tmp
    - name: Modify CentOS Image - Modify User
      vkhitrin.libguestfs.guestfs_user:
        image: '/tmp/CentOS-7-x86_64-GenericCloud-1809.qcow2'
        name: root
        password: 'changeme'
        state: present
